### PR TITLE
[WIP] UI Changes

### PR DESCRIPTION
**Pull request by thePsguy**
Re Issue #5 and #6,
image

@credifiable, could you please help figure out the following,
* What would you suggest would be a good way to arrange the cards in columns here? Is there a bootstrap plugin for react you could recommend?
* The console is throwing the above shown error when a `button` element is placed under a `card`. Why might this be? (course-list.js: line 96 and 128, code below for reference)
```
{availableCourses.map(value => (
	<div key={value.id} >
		<Card variant="raised" className={classes.card}>
			<CardContent>
				<Typography variant="headline" component="h2">
					{value.name}
				</Typography>
				<Typography color="textSecondary">
					{value.shortDescription}
				</Typography>
			</CardContent>
			<CardActions aligh="end">
				<Button
					size="small"
					variant="raised"
					color="primary"
					className={classes.button}
					onClick={() => Router.push({
						pathname: '/course',
						query: { id: value.id },
					})}
				>
  Preview
				</Button>
			</CardActions>
		</Card>
	</div>
))}
```

### CODE REVIEW

**Comment by credifiable** [comment]
Have asked @Praharsh92 to help us on this. He will shortly create a pull request in `enhancements-1`.

Thanks!

**Comment by abhishekgupta92** [comment]
Won't https://react-bootstrap.github.io/layout/grid/ be good enough for the
grid layout of the courses?

--
P.S. Global warming is not cool! Save paper, save earth :)

**Comment by credifiable** [comment]
@abhishekgupta92 - Material UI has it's own grid. No point adding another library for that!

**Comment by credifiable** [comment]
@thePsguy, @abhishekgupta92  - Please check now. Thanks!

**Pull request merged**
