### PR TITLE
[WIP] Authentication

### PR DESCRIPTION
**Pull request by thePsguy**
Used `react-google-login` for auth, login works using client id from angular source.
User object with token received successfully.

Looking into ways to manage a user session and store the received token now.

Tips welcome.

### CODE REVIEW

**Comment by thePsguy** [comment]
Hey @credifiable,

Thanks for the valuable input! I installed web storm for this project and did not realize the default indentation differed from the existing project source, I will update and force a push to my branch.

Thanks for the insight about the material ui and styling as well, I will push this in an additional commit along with user persistence.

Regarding persistence, would [react-cookie](https://www.npmjs.com/package/react-cookie) be a good way to persist and check for user auth status using cookies? 
The user's name and google auth token (required for the saral api from what I understand) should be the only things persisted.

**Comment by credifiable** [comment]
@thePsguy - FWIW, I use atom. :)

> Regarding persistence, would react-cookie be a good way to persist and check for user auth status using cookies?


I don't know about that. It depends on how the auth is implemented currently on saral API. If they use session based authentication, then it is useful to use cookies. If they are using oAuth, I would suggest to persist things in `localstorage`. But again, let @abhishekgupta92 also come back on this!

**Comment by abhishekgupta92** [comment]
We are using OAuth2 :) 

This is our loginUser function. In case it can be of any help. 

`public loginUser(request: Hapi.Request, reply: Hapi.IReply) {

    let auth = new GoogleAuth;
    let client = new auth.OAuth2(this.configs.googleAuth.clientId, '', '');
    client.verifyIdToken(request.payload.idToken, this.configs.googleAuth.clientId, (e, login) => {

        let googleAuthPayload = login.getPayload();

        let isFacilitator = this.configs.facilitatorEmails.indexOf(googleAuthPayload['email']) > -1;
        let userObj = {
            email: googleAuthPayload['email'],
            name: googleAuthPayload['name'],
            profilePicture: googleAuthPayload['picture'],
            googleUserId: googleAuthPayload['sub'],
            facilitator: isFacilitator
        };
        return this.userModel.upsert(userObj, {'email': userObj['email']}, true)
            .then((user) => {
                return reply({
                    'user': user,
                    'jwt': this.userModel.getJWTToken(user)
                });
            });
    });
}`

**Comment by thePsguy** [comment]
Great thanks, I'll look into `localstorage`

@credifiable, So I've been looking to centralize a set of functions to manage the authentication and other api requests, but can't seem to be able to figure out what would work for this setup.
What would you suggest would be a good way to centralize and import? A new component with a class that could be imported maybe?

**Comment by credifiable** [comment]
Hey @thePsguy, sure I would help you with that. I did implement it using central store a while ago, but I think now it can be done in a much more better way. Give me some time to come up with some elegant solution. Meanwhile, you can try and finalise the home page, with course list, and any course detail page, with markdown preview support. If you need any help with that, please do not hesitate to call me. 

Thanks!

**Comment by thePsguy** [comment]
That'd be great thanks!

I'll work on the home page and course list meanwhile.

**Comment by credifiable** [comment]
@abhishekgupta92 - I am super occupied with my day job right now. Planning to take it up on this weekend.

**Comment by thePsguy** [comment]
@abhishekgupta92, I have it figured out, just couldn't get to it yet with my finals coming up this week. Will get it done tonight or the morning by the latest.

**Comment by thePsguy** [comment]
@abhishekgupta92, looking at the homepage, I'll need to fetch courses from the server and would rather do it in one go once the structure of the API is figured out. The design part won't take time, just need to figure out the centralized api thing so can do it in one go smoothly.

**Comment by abhishekgupta92** [comment]
Cool. Over to @credifiable then :)

**Pull request merged**
